---
name: Docker Build and Push
description: Build and push Docker image to GitHub Container Registry
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
    default: ${{ github.token }}
  image_name:
    description: Name of the Docker image (e.g., my-image)
    required: true
  image_tags:
    description: Tags for the Docker image. Split multiple tags with commas (e.g., latest,1.0.0)
    required: true
  context:
    description: 'Build context for Docker (default: .)'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Build and Push Docker Image
      shell: bash
      run: |
        echo "TODO"
