blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/cliff-notes/cliff-notes/wiki
    about: Check out our documentation and guides
  - name: Discussions
    url: https://github.com/cliff-notes/cliff-notes/discussions
    about: Have questions? Start a discussion instead
