---
name: Test Different Actions
on: # # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test with'
        required: true
        default: '0.1.0'

env:
  ACT: ''
  DRY_RUN: 'true'
  IMAGE_ORG: 'camalot'
  IMAGE_REPO: 'cliff-notes'
  IMAGE_NAME: 'cliff-notes'
  PRERELEASE: 'true'
  PRERELEASE_TAG: 'beta'

permissions: {}
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      ver_major_minor_patch: ${{ steps.get.outputs.major_minor_patch }}
      ver_major_minor: ${{ steps.get.outputs.major_minor }}
      ver_major: ${{ steps.get.outputs.major }}
      tag_major_minor_patch: ${{ steps.get.outputs.tag_major_minor_patch }}
      tag_major_minor: ${{ steps.get.outputs.tag_major_minor }}
      tag_major: ${{ steps.get.outputs.tag_major }}
    steps:

    - name: Get Version
      id: get
      env:
        I_VERSION: ${{ github.event.inputs.version }}
      run: |
        VERSION=${I_VERSION:-0.1.0}
        IFS='.' read -r -a parts <<< "$VERSION"
        MAJOR=${parts[0]}
        MINOR=${parts[1]}
        PATCH=${parts[2]}
        echo "MAJOR=$MAJOR"
        echo "MINOR=$MINOR"
        echo "PATCH=$PATCH"

        {
          echo "VERSION=$VERSION"
          echo "major_minor_patch=$MAJOR.$MINOR.$PATCH"
          echo "major_minor=$MAJOR.$MINOR"
          echo "major=$MAJOR"
          echo "tag_major_minor_patch=v$MAJOR.$MINOR.$PATCH"
          echo "tag_major_minor=v$MAJOR.$MINOR"
          echo "tag_major=v$MAJOR"
        } >> $GITHUB_OUTPUT
  package-json:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: version
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Prepare package.json file
      shell: bash
      # we do not commit here. The release call does a commit.
      # if it fails, then we don't commit this change
      run: |
        echo "::group::Prepare package.json"
        # need to find all package.json files that we need to update that are managed by pnpm workspaces
        # get the projects from pnpm-workspace.yaml and update the package.json files in those projects
        # the values in pnpm-workspace.yaml can be globs, so we need to resolve those globs to find the package.json files
        # we also need to update the version in the root package.json file

        projects=$(yq eval '.packages[]' pnpm-workspace.yaml)
        for project in $projects; do
          # resolve the glob to find the package.json files
          files=$(find . -path "./$project/package.json" -type f)
          for file in $files; do
            echo "Updating version in $file"
            echo ".version = \"${VERSION}\" -> $file"
            # yq eval --inplace ".version = \"${VERSION}\"" "$file"
            # git add "$file"
          done
        done
        # yq eval --inplace ".version = \"${VERSION}\"" package.json
        echo ".version = \"${VERSION}\" -> package.json"
        # git add package.json
        echo "::endgroup::"
      env:
        VERSION: ${{ needs.version.outputs.ver_major_minor_patch }}
