---
name: Test Different Actions
on: # # yamllint disable-line rule:truthy
  workflow_dispatch:

env:
  ACT: ''
  DRY_RUN: 'true'
  PACKAGE_OWNER: 'darthminos'
  PACKAGE_NAME: 'cliff-toml'
  VERSION: '0.1.0'

permissions: {}
jobs:
  extension-package:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    outputs:
      artifact-id: ${{ steps.package-extension.outputs.artifact-id }}
      artifact-url: ${{ steps.package-extension.outputs.artifact-url }}
      artifact-digest: ${{ steps.package-extension.outputs.artifact-digest }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Package Extension"
        uses: ./.github/actions/extension/package
        id: package-extension
        with:
          github-token: ${{ github.token }}
          version: ${{ env.VERSION }}
          package-owner: ${{ env.PACKAGE_OWNER }}
          package-name: ${{ env.PACKAGE_NAME }}

      - name: "Extension Package Information"
        shell: bash
        run: |
          {
            echo "## Artifact Information"
            echo ""
            echo "| Artifact ID | Artifact URL | Artifact Digest |"
            echo "|-------------|-------------|----------------|"
            echo "| $ARTIFACT_ID | $ARTIFACT_URL | $ARTIFACT_DIGEST |"
            echo ""
          } >> "$GITHUB_STEP_SUMMARY"
        env:
          ARTIFACT_ID: ${{ steps.package-extension.outputs.artifact-id }}
          ARTIFACT_URL: ${{ steps.package-extension.outputs.artifact-url }}
          ARTIFACT_DIGEST: ${{ steps.package-extension.outputs.artifact-digest }}

  extension-publish:
    runs-on: ubuntu-latest
    needs: extension-package
    permissions:
      deployments: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Publish Extension"
        uses: ./.github/actions/extension/publish
        with:
          github-token: ${{ github.token }}
          artifact-name: ${{ needs.extension-package.outputs.artifact-name }}
          artifact-pattern: '*.vsix'
          dry-run: ${{ env.ACT != '' || env.DRY_RUN == 'true' }}
          vs-marketplace-token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          openvsx-token: ${{ secrets.OPEN_VSX_TOKEN }}
          version: ${{ env.VERSION }}
          package-owner: ${{ env.PACKAGE_OWNER }}
          package-name: ${{ env.PACKAGE_NAME }}
